os: linux
dist: bionic
language: python
services:
- docker
python:
- 3.8
before_install:
- docker run --name madroid-pg -e TZ=Asia/Seoul -e POSTGRES_USER=aurora -e POSTGRES_PASSWORD=password -e POSTGRES_DB=aurora -d postgres:13.4-alpine
- docker ps -a
script:
- pytest -v
