os: linux
dist: bionic
language: python
services:
- docker
python:
- 3.8
before_install:
- docker run -p 127.0.0.1:5432:5432 --name pg-tester -e TZ=Asia/Seoul -e POSTGRES_USER=admin -e
  POSTGRES_PASSWORD=password -e POSTGRES_DB=pg_dev -d postgres:13.4
- docker ps -a
- pip install -r requirements.txt
script:
- pytest -v
